language: rust

matrix:
  include:
    # OS compat
    - os: linux
    - os: linux
      arch: arm64
    - os: osx

    # rustc version compat
    - rust: 1.43.0 # oldest supported version, keep in sync with README.md
    - rust: 1.43.0
      env: EXTRA_FEATURES="dist-server openssl/vendored"
    - rust: beta
    - rust: nightly
      env: EXTRA_FEATURES="unstable"

    # deployments
    - env: DEPLOY=1 TARGET=x86_64-apple-darwin
      script: cargo build --release --target $TARGET --features=openssl/vendored
      os: osx
    - env: DEPLOY=1 TARGET=aarch64-apple-darwin SDKROOT=/Applications/Xcode-12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
      before_script: rustup target add aarch64-apple-darwin
      script: cargo build --release --target $TARGET --features=openssl/vendored
      os: osx
      osx_image: xcode12.2
      rust: beta
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl
      before_script: rustup target add x86_64-unknown-linux-musl
      script: cargo build --release --target $TARGET --features=openssl/vendored
      addons:
        apt:
          packages:
          - musl-tools
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl SUFFIX=-dist
      before_script: rustup target add x86_64-unknown-linux-musl
      script: cargo build --release --target $TARGET --no-default-features --features="openssl/vendored dist-server"
      addons:
        apt:
          packages:
          - musl-tools
    - env: DEPLOY=1 TARGET=aarch64-unknown-linux-musl CC_aarch64_unknown_linux_musl=musl-gcc
      before_script: rustup target add aarch64-unknown-linux-musl
      script: cargo build --release --target $TARGET --features=openssl/vendored
      arch: arm64
      addons:
        apt:
          packages:
          - musl-tools
  allow_failures:
    - rust: nightly

before_script:
  - if [[ "${TRAVIS_RUST_VERSION}" = "stable" ]]; then rustup component add rustfmt && cargo fmt -- --check; fi

script:
  - cargo build --verbose --features="${EXTRA_FEATURES}" || exit 1
  - RUST_BACKTRACE=1 cargo test --all --verbose --no-default-features --features="${EXTRA_FEATURES}" 
  - RUST_BACKTRACE=1 cargo test --all --verbose --features="${EXTRA_FEATURES}"
  - case "${EXTRA_FEATURES}" in *dist-server*) RUST_BACKTRACE=1 cargo test --all --verbose --features="dist-tests ${EXTRA_FEATURES}" test_dist_ -- --test-threads 1 ;; esac

before_deploy:
  - "./scripts/prep_deploy.sh"

deploy:
  api_key:
    secure: rF9ZCpzIJ+pYqxvS20omuTfQ5bN/W81malxwEyRobZc1OrcYK3Gdmq9wwxayx75PgDlXJvIMkuBrkRq1Mc1VprKOLmlg8yPjVm+5G1JySrpZ0yhs2+838gUJkdWESKtZRZ8xhKz2H1tK1a9WMXzWrW/hIBIWA2aZqC7hUTRvIyENE8hDec+7kTQCuNXkcsCL4mF9G77IPQhGR6CYj6Sg5j0u4NsIBiYnd3C218BUkZS15nE37Zj2o3C/ekQsUfAi8e3ALE6WEU+KDRccWT3/F8FMItxlJ5c2Wt4lUL5FC4+b5Vtz6sLBklKc8kex+ClFga5Hq6FDwBnotL8XsBZGiWPssdcZYVWtjHsXT1XeQOrtgdN+VN0IXP7/QzsEHSIADw9RE5S0F9RTKO+ghPL5YU1t7ZbWRqMy+AQDbFreIRftGWHyaRzmmxdea+XdhTMzv8Xyccakek+2HmrkvxC5KBtVVQUcjtf/mdEfF696N+DN4A+dkai15uk8C5vPGWDZF3SDlIOY23dOnMzMkC6qEFrzFjCwJ6mRKUhYI7mU4weMLekKq0dJa7xQuGNP7yuwQ4I+S/X00ukAcvNCLmWWjRRBxxeTVQJDwRdSepbzSkFqP6noopnOw6EIo6YV1EY9ipoX1ahaFVC8480uFFQI1BjVefTvFcflbCiSCerQECU=
  file_glob: true
  file:
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz.sha256
  on:
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true
